# ????? ???? ?
server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    connection-timeout: 30s

spring:
  profiles:
    active: local
  application:
    name: producer
  jackson:
    serialization.fail-on-empty-beans: false
  lifecycle:
    timeout-per-shutdown-phase: 20s


