# local, dev, prd 용도별로

server:
  port: 8888

# jpa ?? ??
spring:
  datasource:
    url:
    username:
    password:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        default_batch-fetch-size: 500

